# Generated by Django 5.2.17 on 2026-09-13 17:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('memo', models.TextField(blank=True, max_length=10000)),
                ('status', models.CharField(choices=[('TENTATIVE', '未確定'), ('CONFIRMED', '確定'), ('COMPLETED', '完了')], default='TENTATIVE', max_length=16)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('duration', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(24)])),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reminded_on', models.DateField(blank=True, null=True)),
                ('version', models.PositiveIntegerField(default=1)),
                ('legacy_id', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['user', 'date'], name='planner_eve_user_id_44b210_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('duration__gte', 1), ('duration__lte', 24)), name='valid_duration'), models.CheckConstraint(condition=models.Q(('status__in', ['TENTATIVE', 'CONFIRMED', 'COMPLETED'])), name='valid_status'), models.CheckConstraint(condition=models.Q(('time__isnull', True), ('date__isnull', False), _connector='OR'), name='time_requires_date'), models.UniqueConstraint(fields=('user', 'legacy_id'), name='unique_user_legacy_event')],
            },
        ),
    ]
